[build]
  publish = "/"
  command = ""

# Redirige la ruta raíz a la página de login.
[[redirects]]
  from = "/"
  to = "/src/login/login.html"
  status = 200

# Opcional: Si un usuario intenta acceder a una ruta que no existe,
# puedes redirigirlo a la página de login en lugar de mostrar un error 404.
[[redirects]]
  from = "/*"
  to = "/src/login/login.html"
  status = 404