[build]
  publish = "/"
  command = ""

# Redirección principal para que la app se cargue desde la raíz.
[[redirects]]
  from = "/"
  to = "/src/login/login.html"
  status = 200

# Regla de reescritura para todas las demás rutas.
# Esto permite que las rutas internas de la app funcionen correctamente.
[[redirects]]
  from = "/*"
  to = "/src/login/login.html"
  status = 200