[build]
  publish = "/"
  command = ""

# Reglas específicas para cada página de tu panel de administrador
# Netlify lee estas reglas de arriba hacia abajo, por eso las específicas van primero.

[[redirects]]
  from = "/src/admin/dashboard.html"
  to = "/src/admin/dashboard"
  status = 200

[[redirects]]
  from = "/admin/historial"
  to = "/src/admin/historial.html"
  status = 200

[[redirects]]
  from = "/admin/usuarios"
  to = "/src/admin/usuarios.html"
  status = 200

# ... y así sucesivamente para todas tus páginas del admin ...


# Regla general al final para manejar el enrutamiento de la app
# y mostrar la página de login si ninguna de las anteriores coincide.
[[redirects]]
  from = "/*"
  to = "/src/login/login.html"
  status = 200