[build]
  # Publica el directorio raíz donde Netlify encontrará los archivos
  publish = "src" 
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecciones específicas para cada rol
[[redirects]]
  from = "/admin/:page"
  to = "/admin/:page.html"
  status = 200

[[redirects]]
  from = "/operario/:page"
  to = "/operario/:page.html"
  status = 200

[[redirects]]
  from = "/supervisor/:page"
  to = "/supervisor/:page.html"
  status = 200